// Code generated by protoc-gen-go. DO NOT EDIT.
// source: collect.proto

package pbevents

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// This type is used to convey info about a collection request; it includes
// auth details that enables the collector to associate intake events with a
// particular client's collection request.
type Collect struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Collect) Reset()         { *m = Collect{} }
func (m *Collect) String() string { return proto.CompactTextString(m) }
func (*Collect) ProtoMessage()    {}
func (*Collect) Descriptor() ([]byte, []int) {
	return fileDescriptor_37ca5d531a1e5e54, []int{0}
}

func (m *Collect) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Collect.Unmarshal(m, b)
}
func (m *Collect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Collect.Marshal(b, m, deterministic)
}
func (m *Collect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Collect.Merge(m, src)
}
func (m *Collect) XXX_Size() int {
	return xxx_messageInfo_Collect.Size(m)
}
func (m *Collect) XXX_DiscardUnknown() {
	xxx_messageInfo_Collect.DiscardUnknown(m)
}

var xxx_messageInfo_Collect proto.InternalMessageInfo

func (m *Collect) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Collect) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*Collect)(nil), "pbevents.Collect")
}

func init() { proto.RegisterFile("collect.proto", fileDescriptor_37ca5d531a1e5e54) }

var fileDescriptor_37ca5d531a1e5e54 = []byte{
	// 92 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0xc9,
	0x49, 0x4d, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x28, 0x48, 0x4a, 0x2d, 0x4b,
	0xcd, 0x2b, 0x29, 0x56, 0xd2, 0xe7, 0x62, 0x77, 0x86, 0x48, 0x09, 0xf1, 0x71, 0x31, 0x65, 0xa6,
	0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x31, 0x65, 0xa6, 0x08, 0x89, 0x70, 0xb1, 0x96, 0xe4,
	0x67, 0xa7, 0xe6, 0x49, 0x30, 0x81, 0x85, 0x20, 0x9c, 0x24, 0x36, 0xb0, 0x09, 0xc6, 0x80, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x68, 0xee, 0xf7, 0x6d, 0x52, 0x00, 0x00, 0x00,
}
