// Code generated by protoc-gen-go. DO NOT EDIT.
// source: inbound.proto

package pbevents

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Inbound_Type int32

const (
	Inbound_UNKNOWN Inbound_Type = 0
	Inbound_JSON    Inbound_Type = 1
	Inbound_YAML    Inbound_Type = 2
	Inbound_XML     Inbound_Type = 3
)

var Inbound_Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "JSON",
	2: "YAML",
	3: "XML",
}

var Inbound_Type_value = map[string]int32{
	"UNKNOWN": 0,
	"JSON":    1,
	"YAML":    2,
	"XML":     3,
}

func (x Inbound_Type) String() string {
	return proto.EnumName(Inbound_Type_name, int32(x))
}

func (Inbound_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d35668a371dd8a27, []int{0, 0}
}

type Inbound_Transport int32

const (
	Inbound_HTTP Inbound_Transport = 0
	Inbound_TCP  Inbound_Transport = 1
	Inbound_UDP  Inbound_Transport = 2
)

var Inbound_Transport_name = map[int32]string{
	0: "HTTP",
	1: "TCP",
	2: "UDP",
}

var Inbound_Transport_value = map[string]int32{
	"HTTP": 0,
	"TCP":  1,
	"UDP":  2,
}

func (x Inbound_Transport) String() string {
	return proto.EnumName(Inbound_Transport_name, int32(x))
}

func (Inbound_Transport) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d35668a371dd8a27, []int{0, 1}
}

// This type is used during data collection -- the collector emits it to the
// inbound queue which is then consumed by the writer.
type Inbound struct {
	Context              *Inbound_Context  `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Type                 Inbound_Type      `protobuf:"varint,2,opt,name=type,proto3,enum=pbevents.Inbound_Type" json:"type,omitempty"`
	Transport            Inbound_Transport `protobuf:"varint,3,opt,name=transport,proto3,enum=pbevents.Inbound_Transport" json:"transport,omitempty"`
	Method               string            `protobuf:"bytes,4,opt,name=method,proto3" json:"method,omitempty"`
	Headers              map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Path                 string            `protobuf:"bytes,6,opt,name=path,proto3" json:"path,omitempty"`
	Body                 []byte            `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Inbound) Reset()         { *m = Inbound{} }
func (m *Inbound) String() string { return proto.CompactTextString(m) }
func (*Inbound) ProtoMessage()    {}
func (*Inbound) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35668a371dd8a27, []int{0}
}

func (m *Inbound) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inbound.Unmarshal(m, b)
}
func (m *Inbound) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inbound.Marshal(b, m, deterministic)
}
func (m *Inbound) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inbound.Merge(m, src)
}
func (m *Inbound) XXX_Size() int {
	return xxx_messageInfo_Inbound.Size(m)
}
func (m *Inbound) XXX_DiscardUnknown() {
	xxx_messageInfo_Inbound.DiscardUnknown(m)
}

var xxx_messageInfo_Inbound proto.InternalMessageInfo

func (m *Inbound) GetContext() *Inbound_Context {
	if m != nil {
		return m.Context
	}
	return nil
}

func (m *Inbound) GetType() Inbound_Type {
	if m != nil {
		return m.Type
	}
	return Inbound_UNKNOWN
}

func (m *Inbound) GetTransport() Inbound_Transport {
	if m != nil {
		return m.Transport
	}
	return Inbound_HTTP
}

func (m *Inbound) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Inbound) GetHeaders() map[string]string {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Inbound) GetPath() string {
	if m != nil {
		return m.Path
	}
	return ""
}

func (m *Inbound) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

// Info indicating which client the inbound message belongs to,
// what collection config the writer should use and debug info.
type Inbound_Context struct {
	Client               *Client  `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Collect              *Collect `protobuf:"bytes,2,opt,name=collect,proto3" json:"collect,omitempty"`
	Info                 *Info    `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Inbound_Context) Reset()         { *m = Inbound_Context{} }
func (m *Inbound_Context) String() string { return proto.CompactTextString(m) }
func (*Inbound_Context) ProtoMessage()    {}
func (*Inbound_Context) Descriptor() ([]byte, []int) {
	return fileDescriptor_d35668a371dd8a27, []int{0, 0}
}

func (m *Inbound_Context) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Inbound_Context.Unmarshal(m, b)
}
func (m *Inbound_Context) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Inbound_Context.Marshal(b, m, deterministic)
}
func (m *Inbound_Context) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Inbound_Context.Merge(m, src)
}
func (m *Inbound_Context) XXX_Size() int {
	return xxx_messageInfo_Inbound_Context.Size(m)
}
func (m *Inbound_Context) XXX_DiscardUnknown() {
	xxx_messageInfo_Inbound_Context.DiscardUnknown(m)
}

var xxx_messageInfo_Inbound_Context proto.InternalMessageInfo

func (m *Inbound_Context) GetClient() *Client {
	if m != nil {
		return m.Client
	}
	return nil
}

func (m *Inbound_Context) GetCollect() *Collect {
	if m != nil {
		return m.Collect
	}
	return nil
}

func (m *Inbound_Context) GetInfo() *Info {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterEnum("pbevents.Inbound_Type", Inbound_Type_name, Inbound_Type_value)
	proto.RegisterEnum("pbevents.Inbound_Transport", Inbound_Transport_name, Inbound_Transport_value)
	proto.RegisterType((*Inbound)(nil), "pbevents.Inbound")
	proto.RegisterMapType((map[string]string)(nil), "pbevents.Inbound.HeadersEntry")
	proto.RegisterType((*Inbound_Context)(nil), "pbevents.Inbound.Context")
}

func init() { proto.RegisterFile("inbound.proto", fileDescriptor_d35668a371dd8a27) }

var fileDescriptor_d35668a371dd8a27 = []byte{
	// 403 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xdf, 0x6b, 0xd4, 0x40,
	0x10, 0xc7, 0xbb, 0x97, 0xf4, 0xd2, 0x4c, 0xae, 0x65, 0x1d, 0xa4, 0xc4, 0x13, 0x24, 0xdc, 0x8b,
	0x41, 0x21, 0x48, 0xfa, 0x52, 0xfb, 0x26, 0xa7, 0x50, 0xb5, 0x4d, 0x8f, 0x35, 0x45, 0x7d, 0xcc,
	0x8f, 0x2d, 0x77, 0x18, 0x77, 0x43, 0x6e, 0x5b, 0xcc, 0xbb, 0xff, 0x96, 0xff, 0x9b, 0xec, 0x6e,
	0x62, 0x0f, 0xce, 0xb7, 0xef, 0xcc, 0x7c, 0x66, 0x92, 0xf9, 0xce, 0xc2, 0xf1, 0x46, 0x94, 0xf2,
	0x5e, 0xd4, 0x49, 0xdb, 0x49, 0x25, 0xf1, 0xa8, 0x2d, 0xf9, 0x03, 0x17, 0x6a, 0x3b, 0x9f, 0x55,
	0xcd, 0x86, 0x0b, 0x65, 0xf3, 0xf3, 0xe3, 0x4a, 0x36, 0x0d, 0xaf, 0xc6, 0x10, 0x36, 0xe2, 0x4e,
	0x5a, 0xbd, 0xf8, 0xe3, 0x82, 0xf7, 0xd1, 0x0e, 0xc1, 0x33, 0xf0, 0x2a, 0x29, 0x14, 0xff, 0xa5,
	0x42, 0x12, 0x91, 0x38, 0x48, 0x9f, 0x25, 0xe3, 0xc0, 0x64, 0x60, 0x92, 0xa5, 0x05, 0xd8, 0x48,
	0xe2, 0x2b, 0x70, 0x55, 0xdf, 0xf2, 0x70, 0x12, 0x91, 0xf8, 0x24, 0x3d, 0xdd, 0xef, 0xc8, 0xfb,
	0x96, 0x33, 0xc3, 0xe0, 0x5b, 0xf0, 0x55, 0x57, 0x88, 0x6d, 0x2b, 0x3b, 0x15, 0x3a, 0xa6, 0xe1,
	0xf9, 0x7f, 0x1a, 0x46, 0x84, 0x3d, 0xd2, 0x78, 0x0a, 0xd3, 0x9f, 0x5c, 0xad, 0x65, 0x1d, 0xba,
	0x11, 0x89, 0x7d, 0x36, 0x44, 0x78, 0x0e, 0xde, 0x9a, 0x17, 0x35, 0xef, 0xb6, 0xe1, 0x61, 0xe4,
	0xc4, 0x41, 0xfa, 0x62, 0x7f, 0xe0, 0xa5, 0x05, 0x3e, 0x08, 0xd5, 0xf5, 0x6c, 0xc4, 0x11, 0xc1,
	0x6d, 0x0b, 0xb5, 0x0e, 0xa7, 0x66, 0x9e, 0xd1, 0x3a, 0x57, 0xca, 0xba, 0x0f, 0xbd, 0x88, 0xc4,
	0x33, 0x66, 0xf4, 0xfc, 0x37, 0x01, 0x6f, 0xd8, 0x1a, 0x63, 0x98, 0x5a, 0x63, 0x07, 0x83, 0xe8,
	0xe3, 0xc7, 0x96, 0x26, 0xcf, 0x86, 0x3a, 0xbe, 0xd6, 0x5e, 0x1a, 0xd3, 0x8d, 0x33, 0x41, 0xfa,
	0x64, 0x07, 0xb5, 0x05, 0x36, 0x12, 0xb8, 0x00, 0x57, 0x9f, 0xc4, 0x58, 0x12, 0xa4, 0x27, 0xbb,
	0x1b, 0xdc, 0x49, 0x66, 0x6a, 0xf3, 0x0b, 0x98, 0xed, 0xee, 0x81, 0x14, 0x9c, 0x1f, 0xbc, 0x37,
	0xff, 0xe1, 0x33, 0x2d, 0xf1, 0x29, 0x1c, 0x3e, 0x14, 0xcd, 0xbd, 0x3d, 0x85, 0xcf, 0x6c, 0x70,
	0x31, 0x39, 0x27, 0x8b, 0x37, 0xe0, 0xea, 0x2b, 0x60, 0x00, 0xde, 0x6d, 0xf6, 0x39, 0xbb, 0xf9,
	0x9a, 0xd1, 0x03, 0x3c, 0x02, 0xf7, 0xd3, 0x97, 0x9b, 0x8c, 0x12, 0xad, 0xbe, 0xbf, 0xbb, 0xbe,
	0xa2, 0x13, 0xf4, 0xc0, 0xf9, 0x76, 0x7d, 0x45, 0x9d, 0xc5, 0x4b, 0xf0, 0xff, 0x9d, 0x41, 0xd7,
	0x2f, 0xf3, 0x7c, 0x45, 0x0f, 0x74, 0x3d, 0x5f, 0xae, 0x28, 0xd1, 0xe2, 0xf6, 0xfd, 0x8a, 0x4e,
	0xca, 0xa9, 0x79, 0x46, 0x67, 0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x5f, 0xa2, 0x73, 0x8a,
	0x02, 0x00, 0x00,
}
